version: "3"

services:
  web:
    image: rashid5925/foodordering
    container_name: foodordering
    ports:
      - "5000:5000"
    restart: always
    
    depends_on:
      - database
    networks:
      - mern-network
  
  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/jenkins/workspace/food-ordering:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge